### ISSUE TITLE
可否支持默认选中

### ISSUE THREAD

**Issue by realchen** [385841539/HorizontalScrollSelectedView#2]
看了下 setData这个方法

this.n = strings.size() / 2;

直接是取中间值，建议这个值可以放开设置
  
嗯 ， 没想那么多 ， 时间长了就没管了 哈哈

**Comment by shikechen** [comment]
@385841539 同意，希望加上这个功能：默认选中第几位。

**Comment by faith-hb** [comment]
添加以下代码，可支持默认索引：

`/**
     * 设置默认选中索引值
     * @param index
     */
    public void setDefSelectIndex(int index) {
        if (index < 0 || index > mStrings.size() - 1) {
            return;
        }
        n = index;
        invalidate();
    }`

**Comment by faith-hb** [comment]
添加以下代码，可支持默认索引：
```
   /**
     * 设置默认选中索引值
     * @param index
     */
    public void setDefSelectIndex(int index) {
        if (index < 0 || index > mStrings.size() - 1) {
            return;
        }
        n = index;
        invalidate();
    }
```
